2018-06-20T05:37:08.232Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'the@thegioididong.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Seller' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-20T05:37:08.236Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'the@thegioididong.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Seller' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'the@thegioididong.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Seller' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-20T05:37:08.443Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'chuyen@chuyenphatnhanh.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Shipper' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-20T05:37:08.444Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'chuyen@chuyenphatnhanh.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Shipper' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'chuyen@chuyenphatnhanh.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Shipper' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-20T05:37:08.496Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'app@theapple.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Provider' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-20T05:37:08.496Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'app@theapple.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Provider' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'app@theapple.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Provider' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-20T05:37:08.630Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'sam@samsung.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Provider' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-20T05:37:08.631Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'sam@samsung.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Provider' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'sam@samsung.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Provider' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-20T05:37:08.771Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'easymoney@easymoneyinc.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.FinanceCo' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-20T05:37:08.772Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'easymoney@easymoneyinc.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.FinanceCo' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'easymoney@easymoneyinc.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.FinanceCo' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-20T05:37:08.806Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'sieu@sieuthidienmay.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Seller' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-20T05:37:08.807Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'sieu@sieuthidienmay.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Seller' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'sieu@sieuthidienmay.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Seller' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-20T05:37:08.862Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID '001' in collection with ID 'Asset:org.acme.Z2BTestNetwork.Order' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-20T05:37:08.862Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID '001' in collection with ID 'Asset:org.acme.Z2BTestNetwork.Order' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID '001' in collection with ID 'Asset:org.acme.Z2BTestNetwork.Order' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-20T05:37:09.026Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'giao@giaohangnhanh.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Shipper' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-20T05:37:09.027Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'giao@giaohangnhanh.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Shipper' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'giao@giaohangnhanh.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Shipper' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-20T05:37:16.799Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: Peer has rejected transaction '523dec41e701cdde4801f6e32d94196a7414a267a7cd8ac5fc363503148bdab1' with code MVCC_READ_CONFLICT","stack":"Error: Error trying invoke business network. Error: Peer has rejected transaction '523dec41e701cdde4801f6e32d94196a7414a267a7cd8ac5fc363503148bdab1' with code MVCC_READ_CONFLICT\n    at _initializeChannel.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-20T05:40:45.349Z ERROR   HLFConnection           :enroll()                 {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-20T05:40:45.350Z ERROR   HLFConnection           :login()                  {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-20T05:42:20.932Z ERROR   HLFConnection           :enroll()                 {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-20T05:42:20.932Z ERROR   HLFConnection           :login()                  {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-20T05:43:55.907Z ERROR   HLFConnection           :enroll()                 {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-20T05:43:55.907Z ERROR   HLFConnection           :login()                  {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-20T05:44:05.136Z ERROR   HLFConnection           :enroll()                 {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-20T05:44:05.137Z ERROR   HLFConnection           :login()                  {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
