2018-06-15T07:52:31.469Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'app@theapple.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Provider' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-15T07:52:31.472Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'app@theapple.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Provider' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'app@theapple.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Provider' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-15T07:52:31.761Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'the@thegioididong.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Seller' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-15T07:52:31.762Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'the@thegioididong.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Seller' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'the@thegioididong.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Seller' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-15T07:52:32.040Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'chuyen@chuyenphatnhanh.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Shipper' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-15T07:52:32.040Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'chuyen@chuyenphatnhanh.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Shipper' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'chuyen@chuyenphatnhanh.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Shipper' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-15T07:52:32.143Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'sam@samsung.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Provider' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-15T07:52:32.143Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'sam@samsung.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Provider' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'sam@samsung.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Provider' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-15T07:52:32.170Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'nga@glorious.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Buyer' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-15T07:52:32.170Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'nga@glorious.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Buyer' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'nga@glorious.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Buyer' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-15T07:52:32.430Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'easymoney@easymoneyinc.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.FinanceCo' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-15T07:52:32.431Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'easymoney@easymoneyinc.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.FinanceCo' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'easymoney@easymoneyinc.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.FinanceCo' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-15T07:52:32.463Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID '001' in collection with ID 'Asset:org.acme.Z2BTestNetwork.Order' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-15T07:52:32.464Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID '001' in collection with ID 'Asset:org.acme.Z2BTestNetwork.Order' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID '001' in collection with ID 'Asset:org.acme.Z2BTestNetwork.Order' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-15T07:52:32.803Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'sieu@sieuthidienmay.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Seller' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-15T07:52:32.804Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'sieu@sieuthidienmay.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Seller' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'sieu@sieuthidienmay.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Seller' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-15T07:52:33.109Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'giao@giaohangnhanh.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Shipper' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-15T07:52:33.110Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'giao@giaohangnhanh.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Shipper' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'giao@giaohangnhanh.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Shipper' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-15T07:52:33.595Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'linh@vinhsang.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Buyer' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-15T07:52:33.596Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'linh@vinhsang.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Buyer' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'linh@vinhsang.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Buyer' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-15T07:52:41.453Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: Peer has rejected transaction 'b45a252e329f4d226d057e61f86b325ecd115078ae579482a15030097e5bf6ba' with code MVCC_READ_CONFLICT","stack":"Error: Error trying invoke business network. Error: Peer has rejected transaction 'b45a252e329f4d226d057e61f86b325ecd115078ae579482a15030097e5bf6ba' with code MVCC_READ_CONFLICT\n    at _initializeChannel.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-15T07:53:05.893Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'Participant:org.acme.Z2BTestNetwork.' in collection with ID '$sysregistries' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-15T07:53:05.894Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'Participant:org.acme.Z2BTestNetwork.' in collection with ID '$sysregistries' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'Participant:org.acme.Z2BTestNetwork.' in collection with ID '$sysregistries' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-15T07:56:02.900Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'Participant:org.acme.Z2BTestNetwork.' in collection with ID '$sysregistries' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-15T07:56:02.901Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'Participant:org.acme.Z2BTestNetwork.' in collection with ID '$sysregistries' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'Participant:org.acme.Z2BTestNetwork.' in collection with ID '$sysregistries' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-15T07:59:25.061Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'linh@vinhsang.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Buyer' does not exist)
    at /home/user/Chapter10/node_modules/composer-connector-hlfv1/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-06-15T07:59:25.062Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'linh@vinhsang.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Buyer' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'linh@vinhsang.com' in collection with ID 'Participant:org.acme.Z2BTestNetwork.Buyer' does not exist)\n    at channel.queryByChaincode.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-06-15T09:20:54.022Z ERROR   HLFConnection           :enroll()                 {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-15T09:20:54.023Z ERROR   HLFConnection           :login()                  {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-15T09:21:24.740Z ERROR   HLFConnection           :enroll()                 {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-15T09:21:24.742Z ERROR   HLFConnection           :login()                  {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-15T09:21:49.315Z ERROR   HLFConnection           :enroll()                 {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-15T09:21:49.315Z ERROR   HLFConnection           :login()                  {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-15T09:22:24.131Z ERROR   HLFConnection           :enroll()                 {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-15T09:22:24.131Z ERROR   HLFConnection           :login()                  {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-15T09:22:44.611Z ERROR   HLFConnection           :enroll()                 {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-15T09:22:44.612Z ERROR   HLFConnection           :login()                  {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-15T09:22:54.851Z ERROR   HLFConnection           :enroll()                 {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-15T09:22:54.851Z ERROR   HLFConnection           :login()                  {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-15T09:23:48.099Z ERROR   HLFConnection           :enroll()                 {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-15T09:23:48.100Z ERROR   HLFConnection           :login()                  {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-15T09:24:45.443Z ERROR   HLFConnection           :enroll()                 {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-15T09:24:45.443Z ERROR   HLFConnection           :login()                  {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-20T04:54:53.604Z ERROR   HLFConnection           :enroll()                 {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-20T04:54:53.604Z ERROR   HLFConnection           :login()                  {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-20T04:55:37.187Z ERROR   HLFConnection           :enroll()                 {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-20T04:55:37.188Z ERROR   HLFConnection           :login()                  {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect EHOSTUNREACH 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-20T04:56:16.692Z ERROR   HLFConnection           :createIdentity()         Register request failed trying to create identity {"0":{"stack":["{Error}fabric-ca request register failed with errors [[{\"code\":0,\"message\":\"Identity 'linh@vinhsang.com' is already registered\"}]] Error: fabric-ca request register failed with errors [[{\"code\":0,\"message\":\"Identity 'linh@vinhsang.com' is already registered\"}]]","    at IncomingMessage.<anonymous> (/home/user/Chapter10/node_modules/fabric-ca-client/lib/FabricCAClientImpl.js:592:22)","    at emitNone (events.js:111:20)","    at IncomingMessage.emit (events.js:208:7)","    at endReadableNT (_stream_readable.js:1064:12)","    at _combinedTickCallback (internal/process/next_tick.js:138:11)","    at process._tickCallback (internal/process/next_tick.js:180:9)"]}}$
2018-06-20T04:56:25.091Z ERROR   HLFConnection           :enroll()                 {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
2018-06-20T04:56:25.091Z ERROR   HLFConnection           :login()                  {"message":"Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]","stack":"Error: Error trying to enroll user or load channel configuration. Error: Calling enrollment endpoint failed with error [Error: connect ETIMEDOUT 10.0.10.29:7054]\n    at caClient.enroll.then.then.then.then.catch (/home/user/Chapter10/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:206:34)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)"}$
